package app.pi.ui.theme

import androidx.compose.ui.graphics.Color
import app.pi.rpc.PiJson
import app.pi.runtime.PiProjectConfig
import java.io.File
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/**
 * Reading pi's theme files into the app's own palette.
 *
 * pi's theme loader is `loadThemeFromPath` in
 * `packages/coding-agent/src/modes/interactive/theme/theme.ts:625`, the document
 * schema is `theme-json.ts:18-97` (its optional `appearance` field is `:22`), and
 * the discovery locations are `core/resource-loader.ts:1042` (the agent dir's
 * `themes` directory and the project's `.pi/themes`) plus whatever the `themes`
 * setting names (`core/settings-manager.ts:1246`). This file reproduces those three
 * things and nothing else:
 *
 *  - **Discovery** of the names the picker may offer, each with the file it came
 *    from, so a theme dropped into `~/.pi/agent/themes` is selectable even though
 *    the `themes` setting never mentions it. (pi does the same in
 *    `getCustomThemeInfos`, `theme.ts:500`.)
 *  - **Colour resolution**, exactly pi 0.99.2's value grammar: `#rgb` / `#rrggbb`,
 *    `oklch(L C H)` / `okhsl(H S L)`, an integer 0-255 (a 256-colour terminal
 *    index), `""` (the terminal's default), or a `vars` reference
 *    (`resolveVarRefs`, `theme.ts:135-151`; see [resolveRaw] for the grammar and
 *    the colour maths).
 *  - **Optional-token fallbacks** from `withThemeColorFallbacks`
 *    (`theme.ts:164-179`) and the HTML exporter's derived page/card/info
 *    backgrounds (`core/export-html/index.ts:81-105`).
 *  - **The built-in pair and `system`**, answered by [load] without reading a user
 *    theme file at all (`addTheme`, `theme.ts:480-483`: the pair ships as JSON beside
 *    the engine, `system` has no document anywhere).
 *
 * What the app cannot honour, it says in [PiResolvedTheme.notes] rather than
 * dropping silently:
 *
 *  - `""` means "use the terminal's foreground/background". A Compose palette has
 *    no terminal, so the built-in theme's value for that token is substituted.
 *  - A 256-colour index is resolved against the standard xterm palette, which is
 *    a guess: the real palette belongs to the terminal app, not to pi.
 *  - `system` is generated by pi from the terminal's reported palette
 *    (`system-theme.ts:32`), which the app's own surfaces never see, so the name is
 *    read as "follow the device's light/dark setting".
 *  - A missing required token cannot be invented, so the built-in value is used
 *    and the token is named in the notes (pi would reject the file outright,
 *    `theme-json.ts:103-137`).
 */

/** Where a theme the app can paint itself with came from. */
enum class PiThemeScope(val label: String) {
    /** pi's built-in `dark` / `light` and the generated `system` (`theme.ts:480-483`). */
    Builtin("内置"),

    /** `~/.pi/agent/themes`, pi's `getCustomThemesDir()`. */
    AgentDir("~/.pi/agent/themes"),

    /** `<cwd>/.pi/themes` — pi's project themes directory. */
    Project("${PiProjectConfig.DIRECTORY}/themes"),

    /** A path or directory named by the `themes` setting. */
    Configured("themes 设置"),
}

/** One selectable theme: its name plus the file backing it (null for built-ins). */
data class PiThemeEntry(
    val name: String,
    val path: String?,
    val scope: PiThemeScope,
)

/** A theme resolved into the app's palette, plus every caveat that applies. */
data class PiResolvedTheme(
    /** The raw `theme` setting, e.g. `dark`, `my-theme`, `light/dark`. */
    val setting: String,
    /** The name actually painted after automatic-pair resolution. */
    val name: String,
    val palette: PiPalette,
    val dark: Boolean,
    val source: PiThemeEntry?,
    /** Things the app could not honour literally, in the user's language. */
    val notes: List<String>,
    /** Non-null when the requested theme could not be used at all. */
    val error: String? = null,
) {
    companion object {
        /** The palette used before the settings file has been read. */
        fun fallback(systemDark: Boolean): PiResolvedTheme {
            val name = if (systemDark) "dark" else "light"
            return PiResolvedTheme(
                setting = name,
                name = name,
                palette = if (systemDark) PiPalette.Dark else PiPalette.Light,
                dark = systemDark,
                source = PiThemeEntry(name, null, PiThemeScope.Builtin),
                notes = emptyList(),
            )
        }
    }
}

/**
 * A theme file that was found and read but cannot be used, with a message
 * written for the user.
 *
 * It exists so [PiThemeLoader.load] can tell "this file says something the app
 * cannot honour" (worth showing, in the user's language) apart from any other
 * failure (worth hiding, because a JVM or library exception's text is not the
 * app's to print). Its `message` is always a complete Chinese sentence naming
 * what is wrong and what to do about it.
 */
private class ThemeParseException(message: String) : Exception(message)

object PiThemeLoader {

    /**
     * pi's reserved built-in name for the terminal-derived theme
     * (`system-theme.ts:32` `export const SYSTEM_THEME_NAME = "system"`). It is
     * 0.99.0's default theme, it has no document on disk, and a custom theme may not
     * take the name (`loadTheme`, `theme.ts:632-633`).
     */
    private const val SYSTEM_THEME_NAME = "system"

    /**
     * `theme-schema.json`'s **51 required** `colors` tokens — the five optional ones
     * live in [OPTIONAL_FALLBACKS] below, so the schema's whole set is 56 (plus the
     * three `export` surfaces, which `parseThemeJson` reads separately).
     */
    private val REQUIRED_TOKENS = listOf(
        "accent", "border", "borderAccent", "borderMuted", "success", "error", "warning",
        "muted", "dim", "text", "thinkingText", "selectedBg", "userMessageBg",
        "userMessageText", "customMessageBg", "customMessageText", "customMessageLabel",
        "toolPendingBg", "toolSuccessBg", "toolErrorBg", "toolTitle", "toolOutput",
        "mdHeading", "mdLink", "mdLinkUrl", "mdCode", "mdCodeBlock", "mdCodeBlockBorder",
        "mdQuote", "mdQuoteBorder", "mdHr", "mdListBullet", "toolDiffAdded",
        "toolDiffRemoved", "toolDiffContext", "syntaxComment", "syntaxKeyword",
        "syntaxFunction", "syntaxVariable", "syntaxString", "syntaxNumber", "syntaxType",
        "syntaxOperator", "syntaxPunctuation", "thinkingOff", "thinkingMinimal",
        "thinkingLow", "thinkingMedium", "thinkingHigh", "thinkingXhigh", "bashMode",
    )

    /** `theme.ts:164-179` `withThemeColorFallbacks`: optional token, and its fallback. */
    private val OPTIONAL_FALLBACKS = mapOf(
        "scrollbarTrack" to "muted",
        "scrollbarThumb" to "text",
        "thinkingMax" to "thinkingXhigh",
        "searchMatchBg" to "selectedBg",
        "searchMatchText" to "text",
    )

    // ------------------------------------------------------------- discovery

    /**
     * Every theme name the app could offer, in the same order pi's
     * `getAvailableThemesWithPaths` (`theme.ts:467-497`) ends up with.
     *
     * `system` has no file and is still a name the picker must know about: pi
     * registers it beside the built-ins (`theme.ts:480-483`) and sorts it first
     * (`:496-497`), and it is 0.99.0's default theme, so a user who picked it in
     * pi's own `/settings` has it in `settings.json`. [load] decides what it means.
     *
     * [configured] is the `themes` setting, verbatim. Entries are guest paths, so
     * they are mapped onto the host tree with [hostPathOf]; a path that cannot be
     * mapped is skipped here and reported by [load] when it is the active theme.
     */
    fun discover(
        agentDir: File,
        workspace: File,
        configured: List<String> = emptyList(),
    ): List<PiThemeEntry> {
        val found = LinkedHashMap<String, PiThemeEntry>()
        for (name in listOf("dark", "light", "system")) {
            found.putIfAbsent(name, PiThemeEntry(name, null, PiThemeScope.Builtin))
        }
        scanDirectory(File(agentDir, "themes"), PiThemeScope.AgentDir, found)
        scanDirectory(PiProjectConfig.themesDir(workspace), PiThemeScope.Project, found)
        for (entry in configured) {
            val file = hostPathOf(entry, agentDir, workspace) ?: continue
            if (file.isDirectory) {
                scanDirectory(file, PiThemeScope.Configured, found)
            } else if (file.isFile && file.name.endsWith(".json")) {
                readEntry(file, PiThemeScope.Configured)?.let { found.putIfAbsent(it.name, it) }
            }
        }
        return found.values.sortedBy { it.name }
    }

    private fun scanDirectory(dir: File, scope: PiThemeScope, into: MutableMap<String, PiThemeEntry>) {
        val files = dir.listFiles() ?: return
        for (file in files.sortedBy { it.name }) {
            if (!file.isFile || !file.name.endsWith(".json")) continue
            val entry = readEntry(file, scope) ?: continue
            into.putIfAbsent(entry.name, entry)
        }
    }

    /**
     * pi takes a theme's name from its document (`name` is required by the schema,
     * `theme-json.ts:20`; `getCustomThemeInfos`, `theme.ts:500-519`); falling back
     * to the file name is this app's own tolerance, for a document that names
     * nothing. `theme.ts:525-531` rejects a name containing `/` because the slash
     * belongs to the automatic pair syntax.
     */
    private fun readEntry(file: File, scope: PiThemeScope): PiThemeEntry? {
        val json = readJson(file) ?: return null
        val declared = json.str("name")?.trim()
        val name = declared?.takeIf { it.isNotEmpty() && !it.contains('/') }
            ?: file.nameWithoutExtension
        if (name.contains('/')) return null
        return PiThemeEntry(name, file.absolutePath, scope)
    }

    // ---------------------------------------------------------------- loading

    /** The resolution used when the setting is absent: pi's own default. */
    fun defaultSetting(systemDark: Boolean): String = if (systemDark) "dark" else "light"

    /**
     * Resolve the `theme` setting into a palette.
     *
     * The automatic form `lightTheme/darkTheme` is one literal string in pi
     * (`parseAutoThemeSetting`, `theme.ts:652-667`); the slash selects which half
     * applies, exactly as `resolveThemeSetting` (`theme.ts:669-680`) does for the
     * terminal's detected background.
     */
    fun load(
        agentDir: File,
        workspace: File,
        configured: List<String>,
        setting: String?,
        systemDark: Boolean,
    ): PiResolvedTheme {
        val raw = setting?.trim().orEmpty().ifEmpty { defaultSetting(systemDark) }
        val slash = raw.indexOf('/')
        val isPair = slash > 0 && raw.indexOf('/', slash + 1) == -1
        val name = if (isPair) {
            val light = raw.substring(0, slash).trim()
            val dark = raw.substring(slash + 1).trim()
            if (systemDark) dark.ifEmpty { "dark" } else light.ifEmpty { "light" }
        } else {
            raw
        }

        if (name == SYSTEM_THEME_NAME) {
            // `system` is the one name pi answers without a theme file: it generates the
            // palette from the terminal's reported colours (`createSystemTheme`,
            // `theme.ts:633`; the name is registered at `:480-483`). Those colours belong
            // to the terminal the TUI runs in, and the app's own surfaces are Compose, so
            // there is nothing to derive from — the honest reading of the name here is
            // "follow the device's light/dark setting", which is the polarity
            // `defaultSetting` and the built-in pair already use. Before this branch the
            // name fell through to `discover()`, found no file, and reported
            // 「找不到主题「system」。」 for what is now pi's default theme.
            val dark = systemDark
            return PiResolvedTheme(
                setting = raw,
                name = name,
                palette = if (dark) PiPalette.Dark else PiPalette.Light,
                dark = dark,
                source = PiThemeEntry(name, null, PiThemeScope.Builtin),
                notes = listOf(
                    "「system」主题由 pi 从终端调色板推导；App 没有终端调色板可用，" +
                        "已按系统的深浅色设置选择内置主题。",
                ),
            )
        }

        if (name == "dark" || name == "light") {
            val dark = name == "dark"
            return PiResolvedTheme(
                setting = raw,
                name = name,
                palette = if (dark) PiPalette.Dark else PiPalette.Light,
                dark = dark,
                source = PiThemeEntry(name, null, PiThemeScope.Builtin),
                notes = emptyList(),
            )
        }

        val entry = discover(agentDir, workspace, configured).firstOrNull { it.name == name }
        val file = entry?.path?.let(::File)
        if (file == null || !file.isFile) {
            return PiResolvedTheme.fallback(systemDark).copy(
                setting = raw,
                error = if (entry != null) {
                    "主题「$name」的文件不存在。"
                } else {
                    "找不到主题「$name」。" +
                        "可以在设置里检查主题名，或直接填写主题文件的路径。"
                },
            )
        }
        val parsed = runCatching { parseTheme(file, systemDark) }.getOrElse { error ->
            // Every user-visible word here is written by this file, never taken
            // from an exception. Two earlier shapes were wrong:
            // `error::class.java.simpleName` printed `FileNotFoundException` to
            // the user, and `error.message` would print whatever a JVM or library
            // exception happens to carry — a path, a token key, a parser's own
            // wording. Only [ThemeParseException] speaks the user's language, so
            // it is the only one whose text is allowed on screen; anything else
            // gets a fixed sentence and keeps its cause in the stack trace.
            return PiResolvedTheme.fallback(systemDark).copy(
                setting = raw,
                error = (error as? ThemeParseException)?.message
                    ?: "主题「$name」读取失败。可以换一个主题，或检查该主题文件的内容。",
            )
        }
        return PiResolvedTheme(
            setting = raw,
            name = name,
            palette = parsed.palette,
            dark = parsed.dark,
            source = entry,
            notes = parsed.notes,
        )
    }

    // ---------------------------------------------------------------- parsing

    private class ParsedTheme(
        val palette: PiPalette,
        val dark: Boolean,
        val notes: List<String>,
    )

    private fun parseTheme(file: File, systemDark: Boolean): ParsedTheme {
        val json = readJson(file)
            ?: throw ThemeParseException("这个主题文件不是合法的 JSON 对象。可以检查文件内容，或换一个主题。")
        return parseThemeJson(json, systemDark)
    }

    private fun parseThemeJson(json: JsonObject, systemDark: Boolean): ParsedTheme {
        val colors = json["colors"] as? JsonObject
            ?: throw ThemeParseException("这个主题文件里没有 colors 一栏。可以检查文件内容，或换一个主题。")
        val vars = json["vars"] as? JsonObject ?: JsonObject(emptyMap())

        // Which built-in palette supplies the values the file cannot express.
        //
        // `appearance` is the file's own answer and wins: pi reads it first and only
        // detects when it is absent (`options.appearance ?? detectAppearance(...)`,
        // `theme.ts:306`; the field is `theme-json.ts:22`). pi's detection weighs every
        // colour the file declares (`detectAppearance`, `theme.ts:229-235`); this app has
        // always used `userMessageBg` alone — the token pi's HTML exporter keys on
        // (`export-html/index.ts:81-105`) — and that stays.
        //
        // What must not stay is `?: true`. "The probe did not resolve" is not evidence
        // that the theme is light: 0.99.2's own `dark.json` spells `userMessageBg` as
        // `blueBg` → `okhsl(233 41% 24%)`, and while the app could not read `okhsl()` the
        // failed probe silently selected `PiPalette.Light` for a dark theme, repainting
        // every falling-back token with the opposite polarity. Now a failed probe falls
        // back to the device's polarity — a value the app actually has — and says so.
        val declared = json.str("appearance")?.trim()?.lowercase()
        val declaredDark = when (declared) {
            "dark" -> true
            "light" -> false
            else -> null
        }
        val probe = resolveRaw(colors["userMessageBg"], vars)
        val probedDark = (probe as? RgbColor)?.let { it.color.isDarkSurface() }
        val isLight = declaredDark?.let { !it } ?: probedDark?.let { !it } ?: !systemDark
        val base = if (isLight) PiPalette.Light else PiPalette.Dark
        val polarityNote = if (declaredDark == null && probedDark == null) {
            "这个主题既没有 appearance 字段，也无法从 userMessageBg 判断深浅；" +
                "已按系统的深浅色设置选择内置的回退配色。"
        } else {
            null
        }

        val notes = mutableListOf<String>()
        if (polarityNote != null) notes += polarityNote
        val emptyTokens = mutableListOf<String>()
        val indexedTokens = mutableListOf<String>()
        val missingTokens = mutableListOf<String>()
        val brokenTokens = mutableListOf<String>()

        val resolved = HashMap<String, Color>()
        for (token in REQUIRED_TOKENS) {
            val element = colors[token]
            if (element == null) {
                missingTokens += token
                resolved[token] = base.token(token)
                continue
            }
            when (val value = resolveRaw(element, vars)) {
                is RgbColor -> resolved[token] = value.color
                is EmptyColor -> {
                    emptyTokens += token
                    resolved[token] = base.token(token)
                }
                is IndexedColor -> {
                    indexedTokens += token
                    resolved[token] = xterm256(value.index)
                }
                else -> {
                    brokenTokens += token
                    resolved[token] = base.token(token)
                }
            }
        }
        // Optional tokens: take the file's value when it has one, otherwise pi's
        // documented fallback token (`theme.ts:164-179`).
        for ((token, fallback) in OPTIONAL_FALLBACKS) {
            val element = colors[token]
            val value = if (element == null) null else resolveRaw(element, vars)
            resolved[token] = when (value) {
                is RgbColor -> value.color
                is IndexedColor -> {
                    indexedTokens += token
                    xterm256(value.index)
                }
                is EmptyColor -> {
                    emptyTokens += token
                    resolved[fallback] ?: base.token(fallback)
                }
                else -> resolved[fallback] ?: base.token(fallback)
            }
        }

        // The `export` section's three surfaces. It is optional; when it is
        // absent pi derives them from `userMessageBg`
        // (`export-html/index.ts:81-105`), which is reproduced here.
        val export = json["export"] as? JsonObject
        for ((token, derived) in deriveExportSurfaces(resolved.getValue("userMessageBg"))) {
            val element = export?.get(token)
            val value = if (element == null) null else resolveRaw(element, vars)
            resolved[token] = when (value) {
                is RgbColor -> value.color
                is IndexedColor -> xterm256(value.index)
                is EmptyColor -> derived
                else -> derived
            }
        }

        if (missingTokens.isNotEmpty()) {
            notes += "缺少这些颜色定义：${missingTokens.joinToString("、")}；这些颜色用内置主题的值代替。"
        }
        if (brokenTokens.isNotEmpty()) {
            notes += "无法解析的颜色：${brokenTokens.joinToString("、")}；已用内置主题的值代替。"
        }
        if (emptyTokens.isNotEmpty()) {
            notes += "这些颜色留空：${emptyTokens.joinToString("、")}；" +
                "已用内置主题的颜色代替。"
        }
        if (indexedTokens.isNotEmpty()) {
            notes += "256 色索引颜色：${indexedTokens.joinToString("、")}；" +
                "已换算成最接近的真彩色。"
        }

        return ParsedTheme(palette = base.withTokens(resolved), dark = !isLight, notes = notes)
    }

    /** The result of resolving one theme colour value. */
    private sealed interface Resolved

    private data class RgbColor(val color: Color) : Resolved

    private object EmptyColor : Resolved

    private data class IndexedColor(val index: Int) : Resolved

    /**
     * pi's value grammar — `resolveVarRefs` (`theme.ts:135-151`), whose literal branch
     * is line **140**:
     *
     * ```ts
     * if (typeof value === "number" || value === "" || value.startsWith("#") || /^ok(lch|hsl)\(/i.test(value)) {
     * ```
     *
     * So a value is a literal when it is a number (a 256-colour index), the empty
     * string (the terminal's default), a `#` string (`#rgb` or `#rrggbb`, see
     * [parseHex]), **or** an `oklch(...)`/`okhsl(...)` colour function (see
     * [parseOkColor]); anything else names a `vars` entry, and a `vars` entry may
     * itself be any of those, so resolution recurses and refuses a cycle.
     *
     * The `/^ok(lch|hsl)\(/i` clause is what 0.99.0 added, and it is a **literal**
     * clause on purpose: without it every colour the 0.99.2 built-in themes are
     * written in (`okhsl(233 41% 24%)`) is looked up as a key in `vars`, is not
     * found, and the token is dropped. That was this app's bug, not the file's.
     */
    private fun resolveRaw(element: JsonElement?, vars: JsonObject, seen: Set<String> = emptySet()): Resolved? {
        val primitive = element as? JsonPrimitive ?: return null
        if (primitive.isString) {
            val text = primitive.content
            if (text.isEmpty()) return EmptyColor
            if (text.startsWith("#")) return parseHex(text)?.let(::RgbColor)
            if (isOkColorFunction(text)) return parseOkColor(text)?.let(::RgbColor)
            if (text in seen) return null
            return resolveRaw(vars[text], vars, seen + text)
        }
        // `JsonPrimitive` has no `intOrNull`; its content is the numeric text.
        val index = primitive.content.toIntOrNull() ?: return null
        return if (index in 0..255) IndexedColor(index) else null
    }

    /** `theme.ts:140`'s `/^ok(lch|hsl)\(/i`, spelled out. */
    private fun isOkColorFunction(text: String): Boolean =
        text.startsWith(prefix = "oklch(", ignoreCase = true) ||
            text.startsWith(prefix = "okhsl(", ignoreCase = true)

    /**
     * `parseColor`'s hex branch (`packages/tui/src/colors.ts:124`):
     * `#rgb` or `#rrggbb`, case-insensitively, and nothing else. A three-digit value is
     * expanded **digit by digit** (`#0af` → `#00aaff`), not shifted — `#0af` is
     * `#00aaff`, not `#0000af`. 0.99.0 added the short form along with the colour
     * functions; before that this function insisted on six digits and dropped the
     * token instead.
     */
    private fun parseHex(text: String): Color? {
        val cleaned = text.removePrefix("#")
        if (cleaned.length != 3 && cleaned.length != 6) return null
        val digits = StringBuilder()
        if (cleaned.length == 3) {
            for (digit in cleaned) {
                digits.append(digit).append(digit)
            }
        } else {
            digits.append(cleaned)
        }
        val value = digits.toString().toLongOrNull(16) ?: return null
        return Color(0xFF000000L or value)
    }

    // ------------------------------------------------- OKLCH / OKHSL -> sRGB

    /*
     * The colour maths below is a literal port of `@earendil-works/pi-tui`'s
     * `dist/oklab.js` (source `packages/tui/src/oklab.ts`): `okhslToRgb`,
     * `oklchToRgb`, `oklabToLinearSrgb`, `linearSrgbToRgb`, `chromaStops`, `cusp`,
     * `maxSaturation`, `maxChroma`, plus the 3x3 matrices and the two hue-direction
     * tables they use. It has to be *this* maths and not an approximation: OKHSL's
     * saturation is relative to the sRGB gamut **at that hue and lightness**, so an
     * ordinary HSL formula paints a plausible-looking but systematically wrong
     * palette — the worst kind of wrong for a colour file.
     *
     * Why it looks conservative on purpose:
     *
     *  - `java.lang.Math` throughout, not `kotlin.math`. `Math.round` rounds ties
     *    towards positive infinity exactly like JavaScript's, where Kotlin's
     *    `round()` rounds ties to even; `Math.pow` is what JavaScript's `**` lowers
     *    to. A one-off rounding difference would move a channel by one and defeat
     *    the point of copying the maths.
     *  - every product, polynomial and Halley step keeps pi's own association, and
     *    the matrices are `Array<DoubleArray>` read row by row, so the port can be
     *    diffed against the original line by line.
     *
     * A second copy of this maths already exists in this repository (`themeColorToRgb`
     * in `tools/pi-contract.mjs`, ~:500): it was checked value-for-value against pi's
     * own `parseColor`/`colorToRgb` over 7541 samples, and this port was written
     * against that copy rather than from memory. `tools/pi-contract.mjs`'s `theme`
     * group now compares the built-in themes token by token through the same maths,
     * so a drift here and a drift there cannot cancel out silently.
     */

    /** `oklab.js`'s `LAB_TO_LMS` (Björn Ottosson's Oklab matrices, MIT). */
    private val OKLAB_LAB_TO_LMS = arrayOf(
        doubleArrayOf(1.0, 0.3963377773761749, 0.2158037573099136),
        doubleArrayOf(1.0, -0.1055613458156586, -0.0638541728258133),
        doubleArrayOf(1.0, -0.0894841775298119, -1.2914855480194092),
    )

    /** `oklab.js`'s `LMS_TO_LINEAR_SRGB`. */
    private val OKLAB_LMS_TO_LINEAR_SRGB = arrayOf(
        doubleArrayOf(4.0767416360759583, -3.3077115392580629, 0.2309699031821043),
        doubleArrayOf(-1.2684379732850315, 2.6097573492876882, -0.341319376002657),
        doubleArrayOf(-0.0041960761386756, -0.7034186179359362, 1.7076146940746117),
    )

    /** `oklab.js`'s `SATURATION_FIT`: per channel, the `(a, b)` half-plane where it clips. */
    private val OKLAB_CLIP_PLANE = arrayOf(
        doubleArrayOf(-1.8817031, -0.80936501),
        doubleArrayOf(1.8144408, -1.19445267),
        doubleArrayOf(0.13110758, 1.81333971),
    )

    /** `oklab.js`'s `SATURATION_FIT`: the polynomial approximating maximum saturation. */
    private val OKLAB_SATURATION_FIT = arrayOf(
        doubleArrayOf(1.19086277, 1.76576728, 0.59662641, 0.75515197, 0.56771245),
        doubleArrayOf(0.73956515, -0.45954404, 0.08285427, 0.12541073, -0.14503204),
        doubleArrayOf(1.35733652, -0.00915799, -1.1513021, -0.50559606, 0.00692167),
    )

    /** `oklab.js`'s `K1` / `K2` / `K3`, the OKHSL lightness curve. */
    private val OKLAB_K1 = 0.206
    private val OKLAB_K2 = 0.03
    private val OKLAB_K3 = (1.0 + OKLAB_K1) / (1.0 + OKLAB_K2)

    /** `colors.ts:90`'s `NUMBER_PATTERN`, verbatim. */
    private const val OK_COLOR_NUMBER = "[+-]?(?:\\d+(?:\\.\\d*)?|\\.\\d+)(?:e[+-]?\\d+)?"

    /**
     * `colors.ts:91-94`'s `OKLCH_PATTERN`, verbatim: **`L C H`**, `L` may carry `%`,
     * the hue may carry `deg`. Note the argument order is the **opposite** of OKHSL's
     * — the one thing about this grammar that is easy to transcribe backwards.
     */
    private val OKLCH_PATTERN = Regex(
        "^oklch\\(\\s*($OK_COLOR_NUMBER)(%)?\\s+($OK_COLOR_NUMBER)\\s+($OK_COLOR_NUMBER)(?:deg)?\\s*\\)$",
        RegexOption.IGNORE_CASE,
    )

    /**
     * `colors.ts:95-98`'s `OKHSL_PATTERN`, verbatim: **`H S L`**, `s` and `l` may
     * carry `%`, the hue may carry `deg`.
     */
    private val OKHSL_PATTERN = Regex(
        "^okhsl\\(\\s*($OK_COLOR_NUMBER)(?:deg)?\\s+($OK_COLOR_NUMBER)(%)?\\s+($OK_COLOR_NUMBER)(%)?\\s*\\)$",
        RegexOption.IGNORE_CASE,
    )

    /**
     * `parseColor`'s two colour-function branches (`colors.ts:134-145`), or `null`
     * when the value is neither — which is `parseColor` throwing
     * (`Invalid color value: ...`), i.e. pi rejecting the theme outright. `null` here
     * becomes the per-token fallback and the 「无法解析的颜色」note, never a guess.
     *
     * Only the *spelling* follows pi's two regular expressions; the argument orders
     * are the ones from [OKLCH_PATTERN] / [OKHSL_PATTERN] above, and a `%` divides by
     * 100 exactly where pi divides by 100.
     */
    private fun parseOkColor(text: String): Color? {
        val oklch = OKLCH_PATTERN.matchEntire(text)
        if (oklch != null) {
            // `groups[...] == null` is "this optional group did not take part", i.e. no `%`.
            val lightness = oklch.groupValues[1].toDoubleOrNull() ?: return null
            val chroma = oklch.groupValues[3].toDoubleOrNull() ?: return null
            val hue = oklch.groupValues[4].toDoubleOrNull() ?: return null
            val l = if (oklch.groups[2] == null) lightness else lightness / 100.0
            // `oklchColor`'s own guards (`colors.ts`): an `l` outside 0-1 or a negative
            // chroma is a **rejected value**, not one to clamp — pi throws
            // `Invalid color value: …` and the theme does not load. Clamping instead would
            // quietly invent a colour pi would have refused, which is the one thing this
            // file must not do.
            if (l < 0.0 || l > 1.0 || chroma < 0.0) return null
            return okChannelsToColor(oklchToRgb(l, chroma, hue))
        }
        val okhsl = OKHSL_PATTERN.matchEntire(text)
        if (okhsl != null) {
            val hue = okhsl.groupValues[1].toDoubleOrNull() ?: return null
            val saturation = okhsl.groupValues[2].toDoubleOrNull() ?: return null
            val lightness = okhsl.groupValues[4].toDoubleOrNull() ?: return null
            val s = if (okhsl.groups[3] == null) saturation else saturation / 100.0
            val l = if (okhsl.groups[5] == null) lightness else lightness / 100.0
            // `okhslColor`'s guards, same reasoning as above. The hue is deliberately
            // unchecked: pi normalises it into 0-360 rather than rejecting it.
            if (s < 0.0 || s > 1.0 || l < 0.0 || l > 1.0) return null
            return okChannelsToColor(okhslToRgb(hue, s, l))
        }
        return null
    }

    /** sRGB channels 0-255 (already clamped by [linearSrgbToRgb]) to a Compose colour. */
    private fun okChannelsToColor(channels: IntArray): Color =
        Color(0xFF000000L or (channels[0].toLong() shl 16) or (channels[1].toLong() shl 8) or channels[2].toLong())

    /** `multiply`: a 3x3 matrix times a 3-vector, both row-major. */
    private fun multiply(matrix: Array<DoubleArray>, vector: DoubleArray): DoubleArray {
        val result = DoubleArray(3)
        for (row in 0..2) {
            result[row] = matrix[row][0] * vector[0] + matrix[row][1] * vector[1] + matrix[row][2] * vector[2]
        }
        return result
    }

    /** JavaScript's `value ** 3`. */
    private fun cubed(value: Double): Double = Math.pow(value, 3.0)

    /** Oklab `[L, a, b]` to linear sRGB `[r, g, b]` (0-1, may leave the gamut). */
    private fun oklabToLinearSrgb(lab: DoubleArray): DoubleArray {
        val lms = multiply(OKLAB_LAB_TO_LMS, lab)
        return multiply(
            OKLAB_LMS_TO_LINEAR_SRGB,
            doubleArrayOf(cubed(lms[0]), cubed(lms[1]), cubed(lms[2])),
        )
    }

    /** sRGB transfer function: linear to encoded, both 0-1. */
    private fun linearToSrgb(value: Double): Double =
        if (value > 0.0031308) 1.055 * Math.pow(value, 1.0 / 2.4) - 0.055 else 12.92 * value

    /** Linear sRGB (0-1) to sRGB channels 0-255, rounded, clipping per channel. */
    private fun linearSrgbToRgb(linear: DoubleArray): IntArray {
        val channels = IntArray(3)
        for (index in 0..2) {
            val encoded = Math.min(1.0, Math.max(0.0, linearToSrgb(linear[index])))
            channels[index] = Math.round(encoded * 255.0).toInt()
        }
        return channels
    }

    /** Rate of change of each cube-root LMS component along the chroma direction `(a, b)`. */
    private fun lmsSlopes(a: Double, b: Double): DoubleArray {
        val slopes = DoubleArray(3)
        for (row in 0..2) {
            slopes[row] = OKLAB_LAB_TO_LMS[row][1] * a + OKLAB_LAB_TO_LMS[row][2] * b
        }
        return slopes
    }

    /** Largest saturation (`C/L`) inside sRGB for hue `(a, b)`: fit plus one Halley step. */
    private fun oklabMaxSaturation(a: Double, b: Double): Double {
        // `SATURATION_FIT.findIndex(([[x, y]], index) => index === 2 || x * a + y * b > 1)`:
        // the third channel is the unconditional answer, so the loop always stops.
        var channel = 2
        for (index in 0..2) {
            if (index == 2 || OKLAB_CLIP_PLANE[index][0] * a + OKLAB_CLIP_PLANE[index][1] * b > 1.0) {
                channel = index
                break
            }
        }
        val fit = OKLAB_SATURATION_FIT[channel]
        val weights = OKLAB_LMS_TO_LINEAR_SRGB[channel]
        val saturation = fit[0] + fit[1] * a + fit[2] * b + fit[3] * a * a + fit[4] * a * b
        val slopes = lmsSlopes(a, b)
        var f = 0.0
        var f1 = 0.0
        var f2 = 0.0
        for (index in 0..2) {
            val base = 1.0 + saturation * slopes[index]
            val first = 3.0 * slopes[index] * Math.pow(base, 2.0)
            val second = 6.0 * Math.pow(slopes[index], 2.0) * base
            f += weights[index] * cubed(base)
            f1 += weights[index] * first
            f2 += weights[index] * second
        }
        return saturation - (f * f1) / (f1 * f1 - 0.5 * f * f2)
    }

    /** Oklab lightness and chroma of the most saturated sRGB colour of hue `(a, b)`. */
    private fun oklabCusp(a: Double, b: Double): DoubleArray {
        val saturation = oklabMaxSaturation(a, b)
        val linear = oklabToLinearSrgb(doubleArrayOf(1.0, saturation * a, saturation * b))
        val lightness = Math.cbrt(1.0 / Math.max(linear[0], Math.max(linear[1], linear[2])))
        return doubleArrayOf(lightness, lightness * saturation)
    }

    /** Chroma where the constant-lightness line at `lightness` leaves the sRGB gamut. */
    private fun oklabMaxChroma(
        a: Double,
        b: Double,
        lightness: Double,
        cuspLightness: Double,
        cuspChroma: Double,
    ): Double {
        if (lightness <= cuspLightness) return (cuspChroma * lightness) / cuspLightness
        // Upper half: triangle edge, then one Halley step against each channel reaching 1.
        val t = (cuspChroma * (lightness - 1.0)) / (cuspLightness - 1.0)
        val slopes = lmsSlopes(a, b)
        val lms = doubleArrayOf(
            lightness + t * slopes[0],
            lightness + t * slopes[1],
            lightness + t * slopes[2],
        )
        val cubes = doubleArrayOf(cubed(lms[0]), cubed(lms[1]), cubed(lms[2]))
        val first = doubleArrayOf(
            3.0 * slopes[0] * Math.pow(lms[0], 2.0),
            3.0 * slopes[1] * Math.pow(lms[1], 2.0),
            3.0 * slopes[2] * Math.pow(lms[2], 2.0),
        )
        val second = doubleArrayOf(
            6.0 * Math.pow(slopes[0], 2.0) * lms[0],
            6.0 * Math.pow(slopes[1], 2.0) * lms[1],
            6.0 * Math.pow(slopes[2], 2.0) * lms[2],
        )
        var step = Double.MAX_VALUE
        for (index in 0..2) {
            val row = OKLAB_LMS_TO_LINEAR_SRGB[index]
            val f = row[0] * cubes[0] + row[1] * cubes[1] + row[2] * cubes[2] - 1.0
            val f1 = row[0] * first[0] + row[1] * first[1] + row[2] * first[2]
            val f2 = row[0] * second[0] + row[1] * second[1] + row[2] * second[2]
            val u = f1 / (f1 * f1 - 0.5 * f * f2)
            if (u >= 0.0) {
                // `Math.min(...steps)`, with `Number.MAX_VALUE` for "this channel never fits".
                val candidate = -f * u
                if (candidate < step) step = candidate
            }
        }
        return t + step
    }

    /** OKHSL's chroma reference points at lightness `L` and hue `(a, b)`: `[c0, cMid, cMax]`. */
    private fun oklabChromaStops(L: Double, a: Double, b: Double): DoubleArray {
        val peak = oklabCusp(a, b)
        val cMax = oklabMaxChroma(a, b, L, peak[0], peak[1])
        val k = cMax / Math.min(
            L * (peak[1] / peak[0]),
            (1.0 - L) * (peak[1] / (1.0 - peak[0])),
        )
        val midS = 0.11516993 +
            1.0 /
            (
                7.4477897 +
                    4.1590124 * b +
                    a *
                    (
                        -2.19557347 +
                            1.75198401 * b +
                            a *
                            (
                                -2.13704948 -
                                    10.02301043 * b +
                                    a * (-4.24894561 + 5.38770819 * b + 4.69891013 * a)
                                )
                        )
                )
        val midT = 0.11239642 +
            1.0 /
            (
                1.6132032 -
                    0.68124379 * b +
                    a *
                    (
                        0.40370612 +
                            0.90148123 * b +
                            a * (-0.27087943 + 0.6122399 * b + a * (0.00299215 - 0.45399568 * b - 0.14661872 * a))
                        )
                )
        val cMid = 0.9 * k * Math.sqrt(
            Math.sqrt(1.0 / (Math.pow(1.0 / (L * midS), 4.0) + Math.pow(1.0 / ((1.0 - L) * midT), 4.0))),
        )
        val c0 = Math.sqrt(
            1.0 / (Math.pow(1.0 / (L * 0.4), 2.0) + Math.pow(1.0 / ((1.0 - L) * 0.8), 2.0)),
        )
        return doubleArrayOf(c0, cMid, cMax)
    }

    /** OKHSL lightness to Oklab lightness. */
    private fun okhslToOklabLightness(x: Double): Double =
        (x * x + OKLAB_K1 * x) / (OKLAB_K3 * (x + OKLAB_K2))

    /**
     * `okhslToRgb`: hue in degrees, saturation and lightness 0-1, to sRGB 0-255.
     * Chroma rises from 0 through `cMid` at `s = 0.8` to `cMax` at `s = 1`, which is
     * the whole point of OKHSL — `s = 1` is the gamut edge at *that* hue and lightness.
     */
    private fun okhslToRgb(hue: Double, saturation: Double, lightness: Double): IntArray {
        val oklabLightness = okhslToOklabLightness(lightness)
        var lab = doubleArrayOf(oklabLightness, 0.0, 0.0)
        if (oklabLightness > 0.0 && oklabLightness < 1.0 && saturation > 0.0) {
            val angle = (2.0 * Math.PI * (((hue % 360.0) + 360.0) % 360.0)) / 360.0
            val a = Math.cos(angle)
            val b = Math.sin(angle)
            val stops = oklabChromaStops(oklabLightness, a, b)
            val c0 = stops[0]
            val cMid = stops[1]
            val cMax = stops[2]
            val chroma: Double
            if (saturation < 0.8) {
                val t = 1.25 * saturation
                val k1 = 0.8 * c0
                chroma = (t * k1) / (1.0 - (1.0 - k1 / cMid) * t)
            } else {
                val t = 5.0 * (saturation - 0.8)
                val k1 = (0.2 * cMid * cMid * Math.pow(1.25, 2.0)) / c0
                chroma = cMid + (t * k1) / (1.0 - (1.0 - k1 / (cMax - cMid)) * t)
            }
            lab = doubleArrayOf(oklabLightness, chroma * a, chroma * b)
        }
        return linearSrgbToRgb(oklabToLinearSrgb(lab))
    }

    /** Whether linear sRGB `[r, g, b]` is inside the gamut, with pi's `1e-7` slack. */
    private fun isInSrgbGamut(linear: DoubleArray): Boolean {
        for (channel in linear) {
            if (channel < -1e-7 || channel > 1.0 + 1e-7) return false
        }
        return true
    }

    /**
     * `oklchToRgb`: OKLCH to sRGB 0-255, gamut-mapped by reducing chroma at a fixed
     * hue. 20 bisection steps, not an approximation to them — pi's own loop, and its
     * comment applies here too: the achromatic colour is always in gamut, so it is the
     * fallback when no step fits (`oklch(100% 0.3 150)` must map to white).
     */
    private fun oklchToRgb(lightness: Double, chroma: Double, hue: Double): IntArray {
        val radians = (hue * Math.PI) / 180.0
        val cos = Math.cos(radians)
        val sin = Math.sin(radians)
        fun atChroma(value: Double): DoubleArray =
            oklabToLinearSrgb(doubleArrayOf(lightness, value * cos, value * sin))

        val direct = atChroma(chroma)
        if (isInSrgbGamut(direct)) return linearSrgbToRgb(direct)
        var linear = atChroma(0.0)
        var low = 0.0
        var high = chroma
        for (step in 0 until 20) {
            val middle = (low + high) / 2.0
            val candidate = atChroma(middle)
            if (isInSrgbGamut(candidate)) {
                low = middle
                linear = candidate
            } else {
                high = middle
            }
        }
        return linearSrgbToRgb(linear)
    }

    /**
     * The 256-colour palette, taken from pi's own table: 16 system colours, the 6x6x6
     * cube (`[0, 95, 135, 175, 215, 255]`), then the 24-step grey ramp
     * (`indexedToRgb`, `packages/tui/src/colors.ts:171-183`).
     *
     * The first 16 are **pi's `BASIC_COLORS`, not the classic xterm defaults**: they
     * differ at 4 (`#000080`, not `#0000ee`), 7 (`#c0c0c0`, not `#e5e5e5`), 8 (`#808080`,
     * not `#7f7f7f`) and 12 (`#0000ff`, not `#5c5cff`). pi's *rendering* path passes the
     * index straight to the terminal (`colorAnsi`: `\x1b[38;5;${index}m`, `colors.ts:299-300`)
     * rather than resolving it, so on a real terminal indices 0-15 are whatever the
     * terminal's palette says — but when pi itself has to resolve one it uses this table,
     * and a phone has no terminal to defer to. Matching pi's table makes the app's
     * approximation the same one pi makes.
     */
    private fun xterm256(index: Int): Color {
        val clamped = index.coerceIn(0, 255)
        val system = intArrayOf(
            0x000000, 0x800000, 0x008000, 0x808000, 0x000080, 0x800080, 0x008080, 0xC0C0C0,
            0x808080, 0xFF0000, 0x00FF00, 0xFFFF00, 0x0000FF, 0xFF00FF, 0x00FFFF, 0xFFFFFF,
        )
        if (clamped < 16) return Color(0xFF000000L or system[clamped].toLong())
        if (clamped < 232) {
            val cube = intArrayOf(0, 95, 135, 175, 215, 255)
            val offset = clamped - 16
            val r = cube[offset / 36]
            val g = cube[(offset % 36) / 6]
            val b = cube[offset % 6]
            return Color(0xFF000000L or (r.toLong() shl 16) or (g.toLong() shl 8) or b.toLong())
        }
        val gray = 8 + (clamped - 232) * 10
        return Color(0xFF000000L or (gray.toLong() shl 16) or (gray.toLong() shl 8) or gray.toLong())
    }

    /**
     * `deriveExportColors` from pi's HTML exporter (`export-html/index.ts:81-105`):
     * light themes keep `userMessageBg` as the card and dim it for the page; dark
     * themes dim it for both and nudge the info surface toward yellow.
     */
    private fun deriveExportSurfaces(userMessageBg: Color): Map<String, Color> {
        val isLight = !userMessageBg.isDarkSurface()
        val page = if (isLight) userMessageBg.scaleRgb(0.96f) else userMessageBg.scaleRgb(0.70f)
        val card = if (isLight) userMessageBg else userMessageBg.scaleRgb(0.85f)
        val info = if (isLight) {
            Color(
                red = ((userMessageBg.red * 255f) + 10f).coerceAtMost(255f) / 255f,
                green = ((userMessageBg.green * 255f) + 5f).coerceAtMost(255f) / 255f,
                blue = ((userMessageBg.blue * 255f) - 20f).coerceAtLeast(0f) / 255f,
            )
        } else {
            Color(
                red = ((userMessageBg.red * 255f) + 20f).coerceAtMost(255f) / 255f,
                green = ((userMessageBg.green * 255f) + 15f).coerceAtMost(255f) / 255f,
                blue = userMessageBg.blue,
            )
        }
        return mapOf("pageBg" to page, "cardBg" to card, "infoBg" to info)
    }

    private fun Color.scaleRgb(factor: Float): Color = Color(
        red = (red * factor).coerceIn(0f, 1f),
        green = (green * factor).coerceIn(0f, 1f),
        blue = (blue * factor).coerceIn(0f, 1f),
    )

    /**
     * Relative luminance, the same test pi's exporter uses (`getLuminance`,
     * `core/export-html/index.ts:64-71`; its `isLight` is `luminance > 0.5`, so this is
     * its `isDark`).
     */
    private fun Color.isDarkSurface(): Boolean {
        fun linear(c: Float): Float =
            if (c <= 0.03928f) c / 12.92f else Math.pow(((c + 0.055f) / 1.055f).toDouble(), 2.4).toFloat()
        val luminance = 0.2126f * linear(red) + 0.7152f * linear(green) + 0.0722f * linear(blue)
        return luminance <= 0.5f
    }

    // ------------------------------------------------------------- host paths

    /**
     * Map one `themes` setting entry onto a host file.
     *
     * The setting holds paths as **pi** sees them (guest spelling, relative to
     * the guest cwd). The two prefixes the app can map without the guest are pi's
     * agent dir and the workspace; anything else is left alone and skipped.
     */
    private fun hostPathOf(entry: String, agentDir: File, workspace: File): File? {
        val path = entry.trim()
        if (path.isEmpty() || path.contains('*') || path.startsWith("!")) return null
        val agentPrefixes = listOf("/root/.pi/agent/", "~/.pi/agent/")
        for (prefix in agentPrefixes) {
            if (path.startsWith(prefix)) return File(agentDir, path.removePrefix(prefix))
        }
        if (path == "/root/.pi/agent" || path == "~/.pi/agent") return agentDir
        if (path.startsWith('/')) return null
        return File(workspace, path.removePrefix("./"))
    }

    private fun readJson(file: File): JsonObject? =
        runCatching { PiJson.parseObjectOrNull(file.readText()) }.getOrNull()

    private fun JsonObject.str(key: String): String? =
        (this[key] as? JsonPrimitive)?.takeIf { it.isString }?.content

    // ----------------------------------------------------------- token mapping

    private fun PiPalette.token(name: String): Color = tokens().getValue(name)

    private fun PiPalette.withTokens(values: Map<String, Color>): PiPalette = PiPalette(
        accent = values.getValue("accent"),
        border = values.getValue("border"),
        borderAccent = values.getValue("borderAccent"),
        borderMuted = values.getValue("borderMuted"),
        success = values.getValue("success"),
        error = values.getValue("error"),
        warning = values.getValue("warning"),
        muted = values.getValue("muted"),
        dim = values.getValue("dim"),
        text = values.getValue("text"),
        thinkingText = values.getValue("thinkingText"),
        selectedBg = values.getValue("selectedBg"),
        scrollbarTrack = values.getValue("scrollbarTrack"),
        scrollbarThumb = values.getValue("scrollbarThumb"),
        searchMatchBg = values.getValue("searchMatchBg"),
        searchMatchText = values.getValue("searchMatchText"),
        userMessageBg = values.getValue("userMessageBg"),
        userMessageText = values.getValue("userMessageText"),
        customMessageBg = values.getValue("customMessageBg"),
        customMessageText = values.getValue("customMessageText"),
        customMessageLabel = values.getValue("customMessageLabel"),
        toolPendingBg = values.getValue("toolPendingBg"),
        toolSuccessBg = values.getValue("toolSuccessBg"),
        toolErrorBg = values.getValue("toolErrorBg"),
        toolTitle = values.getValue("toolTitle"),
        toolOutput = values.getValue("toolOutput"),
        mdHeading = values.getValue("mdHeading"),
        mdLink = values.getValue("mdLink"),
        mdLinkUrl = values.getValue("mdLinkUrl"),
        mdCode = values.getValue("mdCode"),
        mdCodeBlock = values.getValue("mdCodeBlock"),
        mdCodeBlockBorder = values.getValue("mdCodeBlockBorder"),
        mdQuote = values.getValue("mdQuote"),
        mdQuoteBorder = values.getValue("mdQuoteBorder"),
        mdHr = values.getValue("mdHr"),
        mdListBullet = values.getValue("mdListBullet"),
        toolDiffAdded = values.getValue("toolDiffAdded"),
        toolDiffRemoved = values.getValue("toolDiffRemoved"),
        toolDiffContext = values.getValue("toolDiffContext"),
        syntaxComment = values.getValue("syntaxComment"),
        syntaxKeyword = values.getValue("syntaxKeyword"),
        syntaxFunction = values.getValue("syntaxFunction"),
        syntaxVariable = values.getValue("syntaxVariable"),
        syntaxString = values.getValue("syntaxString"),
        syntaxNumber = values.getValue("syntaxNumber"),
        syntaxType = values.getValue("syntaxType"),
        syntaxOperator = values.getValue("syntaxOperator"),
        syntaxPunctuation = values.getValue("syntaxPunctuation"),
        thinkingOff = values.getValue("thinkingOff"),
        thinkingMinimal = values.getValue("thinkingMinimal"),
        thinkingLow = values.getValue("thinkingLow"),
        thinkingMedium = values.getValue("thinkingMedium"),
        thinkingHigh = values.getValue("thinkingHigh"),
        thinkingXhigh = values.getValue("thinkingXhigh"),
        thinkingMax = values.getValue("thinkingMax"),
        bashMode = values.getValue("bashMode"),
        pageBg = values.getValue("pageBg"),
        cardBg = values.getValue("cardBg"),
        infoBg = values.getValue("infoBg"),
    )

    /** Every token as a map, so a parsed file can override any subset of them. */
    private fun PiPalette.tokens(): Map<String, Color> = mapOf(
        "accent" to accent,
        "border" to border,
        "borderAccent" to borderAccent,
        "borderMuted" to borderMuted,
        "success" to success,
        "error" to error,
        "warning" to warning,
        "muted" to muted,
        "dim" to dim,
        "text" to text,
        "thinkingText" to thinkingText,
        "selectedBg" to selectedBg,
        "scrollbarTrack" to scrollbarTrack,
        "scrollbarThumb" to scrollbarThumb,
        "searchMatchBg" to searchMatchBg,
        "searchMatchText" to searchMatchText,
        "userMessageBg" to userMessageBg,
        "userMessageText" to userMessageText,
        "customMessageBg" to customMessageBg,
        "customMessageText" to customMessageText,
        "customMessageLabel" to customMessageLabel,
        "toolPendingBg" to toolPendingBg,
        "toolSuccessBg" to toolSuccessBg,
        "toolErrorBg" to toolErrorBg,
        "toolTitle" to toolTitle,
        "toolOutput" to toolOutput,
        "mdHeading" to mdHeading,
        "mdLink" to mdLink,
        "mdLinkUrl" to mdLinkUrl,
        "mdCode" to mdCode,
        "mdCodeBlock" to mdCodeBlock,
        "mdCodeBlockBorder" to mdCodeBlockBorder,
        "mdQuote" to mdQuote,
        "mdQuoteBorder" to mdQuoteBorder,
        "mdHr" to mdHr,
        "mdListBullet" to mdListBullet,
        "toolDiffAdded" to toolDiffAdded,
        "toolDiffRemoved" to toolDiffRemoved,
        "toolDiffContext" to toolDiffContext,
        "syntaxComment" to syntaxComment,
        "syntaxKeyword" to syntaxKeyword,
        "syntaxFunction" to syntaxFunction,
        "syntaxVariable" to syntaxVariable,
        "syntaxString" to syntaxString,
        "syntaxNumber" to syntaxNumber,
        "syntaxType" to syntaxType,
        "syntaxOperator" to syntaxOperator,
        "syntaxPunctuation" to syntaxPunctuation,
        "thinkingOff" to thinkingOff,
        "thinkingMinimal" to thinkingMinimal,
        "thinkingLow" to thinkingLow,
        "thinkingMedium" to thinkingMedium,
        "thinkingHigh" to thinkingHigh,
        "thinkingXhigh" to thinkingXhigh,
        "thinkingMax" to thinkingMax,
        "bashMode" to bashMode,
        "pageBg" to pageBg,
        "cardBg" to cardBg,
        "infoBg" to infoBg,
    )
}
