/**
 * highlight.js language aliases: every name highlight.js resolves that is not
 * also a file under its own `lib/languages` directory.
 *
 * **Why this table exists.** pi asks highlight.js whether it knows a language
 * (`supportsLanguage` -> `getLanguage`, `utils/syntax-highlight.ts:210-212`), and
 * highlight.js answers for aliases exactly as it does for canonical names. This
 * extension cannot register 191 languages on a phone, so it answered from a
 * directory listing instead — which meant a fence labelled `html`, `toml`,
 * `c++`, `c#`, `golang`, `docker`, `bat` or `hbs` was reported as unknown and
 * rendered plain, while pi colours all of them. Resolving the name to the file
 * that declares it and registering *that* file reproduces the engine: a
 * language definition carries its own aliases, so `registerLanguage` installs
 * them and `highlight({ language: "html" })` then resolves inside highlight.js
 * as it always did.
 *
 * **Where it comes from.** Generated from highlight.js 10.7.3's own
 * `lib/index.js` registration order (a later registration wins, aliases
 * included), then verified row by row by object identity against the engine's
 * registry — 173 rows, 0 mismatches. `tools/pi-highlight-check.mjs` repeats both
 * steps on every run, so a highlight.js upgrade cannot leave this table stale
 * without failing the check.
 *
 * **Cost.** Consulted only when the requested name has no language file of its
 * own ([resolveLanguageFile] in `./hljs`), so the ordinary path is unchanged and
 * never touches this module's data.
 */
export const LANGUAGE_ALIASES: Record<string, string> = {
	"ado": "stata",
	"adoc": "asciidoc",
	"ahk": "autohotkey",
	"apacheconf": "apache",
	"arm": "armasm",
	"as": "actionscript",
	"asc": "angelscript",
	"atom": "xml",
	"bat": "dos",
	"bf": "brainfuck",
	"bind": "dns",
	"c#": "csharp",
	"c++": "cpp",
	"capnp": "capnproto",
	"cc": "cpp",
	"cjs": "javascript",
	"clj": "clojure",
	"cls": "cos",
	"cmake.in": "cmake",
	"cmd": "dos",
	"coffee": "coffeescript",
	"console": "shell",
	"cr": "crystal",
	"craftcms": "twig",
	"crm": "crmsh",
	"cs": "csharp",
	"cson": "coffeescript",
	"cxx": "cpp",
	"dcl": "clean",
	"dfm": "delphi",
	"do": "stata",
	"docker": "dockerfile",
	"dpr": "delphi",
	"dst": "dust",
	"erl": "erlang",
	"f90": "fortran",
	"f95": "fortran",
	"feature": "gherkin",
	"freepascal": "delphi",
	"fs": "fsharp",
	"gemspec": "ruby",
	"gms": "gams",
	"golang": "go",
	"graph": "roboconf",
	"gss": "gauss",
	"gyp": "python",
	"h": "c",
	"h++": "cpp",
	"hbs": "htmlbars",
	"hh": "cpp",
	"hpp": "cpp",
	"hs": "haskell",
	"html": "xml",
	"html.handlebars": "htmlbars",
	"html.hbs": "htmlbars",
	"https": "http",
	"hx": "haxe",
	"hxx": "cpp",
	"hylang": "hy",
	"i7": "inform7",
	"iced": "coffeescript",
	"icl": "clean",
	"ino": "arduino",
	"instances": "roboconf",
	"ipython": "python",
	"irb": "ruby",
	"jinja": "django",
	"js": "javascript",
	"jsp": "java",
	"jsx": "javascript",
	"k": "q",
	"kdb": "q",
	"kt": "kotlin",
	"kts": "kotlin",
	"lassoscript": "lasso",
	"lazarus": "delphi",
	"lfm": "delphi",
	"lpr": "delphi",
	"ls": "livescript",
	"m": "mercury",
	"mak": "makefile",
	"make": "makefile",
	"md": "markdown",
	"mikrotik": "routeros",
	"mips": "mipsasm",
	"mjs": "javascript",
	"mk": "makefile",
	"mkd": "markdown",
	"mkdown": "markdown",
	"ml": "sml",
	"mm": "objectivec",
	"mma": "mathematica",
	"moo": "mercury",
	"moon": "moonscript",
	"mysql": "sql_more",
	"nc": "gcode",
	"nginxconf": "nginx",
	"nixos": "nix",
	"obj-c": "objectivec",
	"obj-c++": "objectivec",
	"objc": "objectivec",
	"objective-c++": "objectivec",
	"oracle": "sql_more",
	"osascript": "applescript",
	"p21": "step21",
	"pas": "delphi",
	"pascal": "delphi",
	"patch": "diff",
	"pb": "purebasic",
	"pbi": "purebasic",
	"pcmk": "crmsh",
	"pf.conf": "pf",
	"php3": "php",
	"php4": "php",
	"php5": "php",
	"php6": "php",
	"php7": "php",
	"php8": "php",
	"pl": "perl",
	"plist": "xml",
	"pm": "perl",
	"podspec": "ruby",
	"postgres": "pgsql",
	"postgresql": "pgsql",
	"pp": "puppet",
	"ps": "powershell",
	"ps1": "powershell",
	"py": "python",
	"pycon": "python-repl",
	"qt": "qml",
	"rb": "ruby",
	"re": "reasonml",
	"rs": "rust",
	"rss": "xml",
	"scad": "openscad",
	"sci": "scilab",
	"sh": "bash",
	"st": "smalltalk",
	"stanfuncs": "stan",
	"step": "step21",
	"stp": "step21",
	"styl": "stylus",
	"sv": "verilog",
	"svg": "xml",
	"svh": "verilog",
	"tao": "xl",
	"tex": "latex",
	"text": "plaintext",
	"thor": "ruby",
	"tk": "tcl",
	"toml": "ini",
	"ts": "typescript",
	"tsx": "typescript",
	"txt": "plaintext",
	"v": "verilog",
	"vb": "vbnet",
	"vbs": "vbscript",
	"wildfly-cli": "jboss-cli",
	"wl": "mathematica",
	"wsf": "xml",
	"x++": "axapta",
	"xhtml": "xml",
	"xjb": "xml",
	"xls": "excel",
	"xlsx": "excel",
	"xpath": "xquery",
	"xq": "xquery",
	"xsd": "xml",
	"xsl": "xml",
	"yml": "yaml",
	"zep": "zephir",
	"zone": "dns",
	"zsh": "bash",
};
