#!/usr/bin/env bash
# Fast Kotlin typecheck without Gradle, and without AAPT2.
#
# Why this exists: the only supported way to build an Android APK is Gradle, and
# Gradle needs AAPT2 — which Google ships for Linux as an **x86_64** binary, so an
# aarch64 workstation cannot run it. On this project the build machine is a phone,
# where a Gradle run is also slow enough to be disruptive. Neither is a good
# reason to push an unchecked change to CI and wait minutes for a typo.
#
# AAPT2 is only needed for *resource* processing. Everything the Kotlin compiler
# needs can be assembled by hand:
#
#   - every jar in the Gradle module cache (Compose, AndroidX, lifecycle, ...)
#   - android.jar from the platform
#   - the `:rpc` module as *sources* on the same command line, not as a jar
#   - a generated stub for the `R` class that AAPT2 would have produced
#
# What it does NOT do: run the Compose compiler plugin (its jar is not a normal
# dependency) and therefore does NOT check composable-call rules or `@OptIn`
# necessity. It catches unresolved references, wrong named arguments, bad types
# and syntax — the failure modes that actually cost CI round trips.
#
# `:rpc` is compiled to a jar FIRST and `:app` is then compiled against that jar,
# rather than both being passed as sources in one invocation. Passing them
# together would let `:app` see `:rpc`'s declarations as same-module, which
# silently hides Kotlin's cross-module smart-cast restriction — a real error that
# only appears in the Gradle build. (Verified: three such errors were found in
# `ui/blocks` once this script started reproducing the boundary.)
#
# The pass/fail verdict is based on whether any `error:` diagnostic was emitted,
# not on the compiler's exit status: codegen cannot complete without the Compose
# plugin, so the JVM exits non-zero even on a clean frontend.
#
#   tools/typecheck.sh                 # everything
#   tools/typecheck.sh --changed       # only files newer than the last run

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${GRADLE_USER_HOME:-$HOME/.gradle}/caches/modules-2/files-2.1"
STUB="$ROOT/build/typecheck/R-stub"
OK=0

if [ ! -d "$CACHE" ]; then
  echo "no Gradle cache at $CACHE — run a build once first" >&2
  exit 2
fi

# --- 1. classpath: every non-source jar in the cache, plus the platform ---------
# AndroidX and Compose ship as **.aar**, not .jar, so globbing the cache alone
# misses every one of them. Their `classes.jar` is extracted once into
# build/typecheck/aar/<artifact>/ and added to the classpath.
CP="$(find "$CACHE" -name '*.jar' \
        ! -name '*-sources.jar' ! -name '*-javadoc.jar' \
        ! -path '*kotlin-compiler*' 2>/dev/null | tr '\n' ':')"
# Dependencies Gradle downloads but Gradle's own cache cannot supply here: this
# script never resolves configurations, so anything the last Gradle run did not
# happen to fetch has to be staged. tools/fetch-typecheck-deps.sh puts the
# markdown renderer (an .aar) and its parser here, ahead of the cache so that
# resolution order matches what Gradle would pick (newest version wins).
EXTRA_DIR="$ROOT/build/typecheck/extra"
EXTRA_CP="$(find "$EXTRA_DIR" -maxdepth 1 -name '*.jar' 2>/dev/null | tr '\n' ':')"
EXTRA_CP="$EXTRA_CP$(find "$EXTRA_DIR/aar" -name 'classes.jar' 2>/dev/null | tr '\n' ':')"
CP="$EXTRA_CP$CP"
AAR_DIR="$ROOT/build/typecheck/aar"
mkdir -p "$AAR_DIR"
while IFS= read -r aar; do
  name="$(basename "$aar" .aar)"
  target="$AAR_DIR/$name"
  [ -f "$target/classes.jar" ] && continue
  mkdir -p "$target"
  python3 - "$aar" "$target/classes.jar" <<'PY' 2>/dev/null || true
import sys, zipfile
try:
    with zipfile.ZipFile(sys.argv[1]) as z:
        if "classes.jar" in z.namelist():
            open(sys.argv[2], "wb").write(z.read("classes.jar"))
except Exception:
    pass
PY
done < <(find "$CACHE" -name '*.aar' 2>/dev/null)
CP="$CP$(find "$AAR_DIR" -name 'classes.jar' 2>/dev/null | tr '\n' ':')"
SDK_DIR="$(sed -n 's/^sdk\.dir=//p' "$ROOT/local.properties" 2>/dev/null)"
SDK_DIR="${SDK_DIR:-/opt/android-sdk}"
ANDROID_JAR="$(ls "$SDK_DIR"/platforms/android-*/android.jar 2>/dev/null | sort | tail -1)"
if [ -z "$ANDROID_JAR" ]; then
  echo "no android.jar under $SDK_DIR/platforms — install a platform" >&2
  exit 2
fi
CP="$CP$ANDROID_JAR"

# --- 2. R stub: AAPT2 would generate this from res/values ----------------------
rm -rf "$STUB"; mkdir -p "$STUB"
{
  echo "package app.pi"
  echo "// Generated by tools/typecheck.sh. Stand-in for AAPT2's R class."
  echo "object R {"
  for kind in string drawable color mipmap xml; do
    names="$(grep -rhoE "R\.$kind\.[A-Za-z_][A-Za-z0-9_]*" "$ROOT/app/src/main/kotlin" 2>/dev/null \
             | sed "s/R\.$kind\.//" | sort -u)"
    [ -z "$names" ] && continue
    echo "  object $kind {"
    for n in $names; do echo "    const val $n: Int = 0"; done
    echo "  }"
  done
  echo "}"
} > "$STUB/R.kt"

# --- 3. sources ----------------------------------------------------------------
# APP_SOURCES must never contain `:rpc` sources: passing them would make the two
# modules one compilation unit and hide the cross-module smart-cast restriction
# this script exists to surface.
if [ "${1:-}" = "--changed" ]; then
  # Only the files touched since the last successful run, plus everything if the
  # marker is missing. Coarse, but the point is a fast pre-push check.
  MARKER="$ROOT/build/typecheck/last"
  if [ -f "$MARKER" ]; then
    APP_SOURCES="$(find "$ROOT/app/src/main/kotlin" -name '*.kt' -newer "$MARKER")"
  else
    APP_SOURCES=""
  fi
  if [ -z "$APP_SOURCES" ]; then echo "nothing changed since last typecheck"; exit 0; fi
else
  APP_SOURCES="$(find "$ROOT/app/src/main/kotlin" -name '*.kt')"
fi

KOTLINC_LIBS="$ROOT/build/typecheck/kotlinc"
if [ ! -d "$KOTLINC_LIBS" ]; then
  echo "missing $KOTLINC_LIBS — see the header of this script" >&2
  exit 2
fi

mkdir -p "$ROOT/build/typecheck/out"
KOTLINC_CP="$(find -L "$KOTLINC_LIBS" -name '*.jar' | tr '\n' ':')"

# Fail loudly when the compiler cannot even start. Without this the script is a
# liar: `java -cp ''` prints "Could not find or load main class", no `.kt:…:
# error:` line ever appears, and the gate below reports "typecheck: OK". That
# actually happened once (a symlinked lib dir, which `find` does not descend
# into without -L) — a green verdict on a tree that was never compiled is worse
# than a red one, because it is trusted.
if [ -z "$KOTLINC_CP" ] || [[ "$KOTLINC_CP" != *kotlin-compiler* ]]; then
  echo "typecheck: CANNOT RUN — no kotlin compiler jars found in $KOTLINC_LIBS" >&2
  echo "  KOTLINC_CP='$KOTLINC_CP'" >&2
  exit 2
fi
# Per-invocation output dir. Several agents run this script at once, and a shared
# OUT means they delete each other's class files mid-compile — which shows up as
# spurious "unresolved reference" errors in files nobody touched. Cheap to avoid.
OUT="$ROOT/build/typecheck/out-$$"
trap 'rm -rf "$OUT"' EXIT
RPC_JAR="$ROOT/build/typecheck/rpc.jar"

compile() {
  # $1 = output dir/jar target, $2 = classpath, rest = sources
  local target="$1"; shift
  local cp="$1"; shift
  local out
  out="$(java -Xmx1100m -Dfile.encoding=UTF-8 -cp "$KOTLINC_CP" \
    org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
    -no-stdlib -jvm-target 17 -classpath "$cp" -d "$target" "$@" 2>&1)"
  # A JVM that failed to launch produces no Kotlin diagnostics at all, which the
  # verdict below would read as success. Turn that into an explicit failure.
  #
  # Matched with `[[ == *pat* ]]` rather than `echo | grep -q`: under `pipefail` a
  # large $out makes grep exit early on SIGPIPE (141), so the guard that exists to
  # catch "the compiler never ran" would itself be skipped on exactly the runs with
  # the most output. That is a false-OK channel, not a theoretical one.
  if [[ "$out" == *"Could not find or load main class"* ||
        "$out" == *"Unrecognized option"* ||
        "$out" == *"Could not reserve enough space"* ]]; then
    echo "typecheck: CANNOT RUN — the compiler did not start:" >&2
    echo "$out" | head -3 >&2
    exit 2
  fi
  echo "$out"
}

# --- stage 1: :rpc as its own module, producing a jar --------------------------
RPC_SOURCES="$(find "$ROOT/rpc/src/main/kotlin" -name '*.kt')"
if [ -n "$RPC_SOURCES" ]; then
  rm -rf "$OUT/rpc"; mkdir -p "$OUT/rpc"
  RPC_DIAG="$(compile "$OUT/rpc" "$CP" $RPC_SOURCES)"
  echo "$RPC_DIAG" | grep -E "\.kt:[0-9]+:[0-9]+: error:" | sed "s|$ROOT/||"
  RPC_ERRS="$(echo "$RPC_DIAG" | grep -cE "\.kt:[0-9]+:[0-9]+: error:")"
  if [ "$RPC_ERRS" -gt 0 ]; then
    echo "typecheck: FAILED in :rpc — $RPC_ERRS error diagnostic(s)"
    exit 1
  fi
  (cd "$OUT/rpc" && jar cf "$RPC_JAR" .) 2>/dev/null
  # A jar built from an empty directory is still a valid jar. When :rpc's compile is
  # killed (this machine throws `fork: Function not implemented` under load) the empty
  # jar makes :app emit hundreds of fake `unresolved reference 'rpc'` diagnostics —
  # 946 of them were once read as real defects. Refuse to continue instead.
  RPC_CLASSES="$(jar tf "$RPC_JAR" 2>/dev/null | grep -c '\.class$')"
  if [ "${RPC_CLASSES:-0}" -eq 0 ]; then
    echo "typecheck: CANNOT RUN — :rpc produced an empty jar ($RPC_JAR)" >&2
    echo "  any :app 'unresolved reference rpc' would be an artifact, not a defect" >&2
    exit 2
  fi
fi

# --- stage 2: :app against the :rpc jar ----------------------------------------
APP_SOURCES="$APP_SOURCES $(find "$STUB" -name '*.kt')"
rm -rf "$OUT/app"; mkdir -p "$OUT/app"
APP_DIAG="$(compile "$OUT/app" "$CP:$RPC_JAR" $APP_SOURCES)"
echo "$APP_DIAG" | grep -E "\.kt:[0-9]+:[0-9]+: error:" | sed "s|$ROOT/||"
APP_ERRS="$(echo "$APP_DIAG" | grep -cE "\.kt:[0-9]+:[0-9]+: error:")"
if [ "$APP_ERRS" -gt 0 ]; then
  echo "typecheck: FAILED in :app — $APP_ERRS error diagnostic(s)"
  exit 1
fi

mkdir -p "$(dirname "$ROOT/build/typecheck/last")"
touch "$ROOT/build/typecheck/last"
# The verdict states the error count it is based on. Appending it rather than
# rewording keeps every existing `grep "typecheck: OK"` working, while removing the
# one thing that made this script lie: a bare "OK" that could not be told apart
# from a run whose diagnostics were lost in a shared or truncated log.
echo "typecheck: OK (:rpc + :app, cross-module boundary reproduced) — 0 error diagnostics, :rpc $RPC_ERRS / :app $APP_ERRS"
exit 0
